openapi: "3.0.0"
info:
  title: "Todo List API"
  version: "1.0.0"
  description: "An API for managing todo lists"
paths:
  /todos:
    get:
      summary: "Get all todos"
      responses:
        "200":
          description: "A list of todos"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties:
                    id:
                      type: "integer"
                    title:
                      type: "string"
                    completed:
                      type: "boolean"
    # post:
    #   summary: "Create a new todo"
    #   requestBody:
    #     required: true
    #     content:
    #       application/json:
    #         schema:
    #           type: "object"
    #           properties:
    #             title:
    #               type: "string"
    #             completed:
    #               type: "boolean"
    #   responses:
    #     "201":
    #       description: "Todo created successfully"
    #       content:
    #         application/json:
    #           schema:
    #             type: "object"
    #             properties:
    #               id:
    #                 type: "integer"
    #               title:
    #                 type: "string"
    #               completed:
    #                 type: "boolean"
  # /todos/{id}:
  #   get:
  #     summary: "Get a todo by ID"
  #     parameters:
  #       - in: path
  #         name: id
  #         required: true
  #         schema:
  #           type: integer
  #     responses:
  #       "200":
  #         description: "A single todo"
  #         content:
  #           application/json:
  #             schema:
  #               type: "object"
  #               properties:
  #                 id:
  #                   type: "integer"
  #                 title:
  #                   type: "string"
  #                 completed:
  #                   type: "boolean"
  # put:
  #   summary: "Update a todo by ID"
  #   parameters:
  #     - in: path
  #       name: id
  #       required: true
  #       schema:
  #         type: integer
  #   requestBody:
  #     required: true
  #     content:
  #       application/json:
  #         schema:
  #           type: "object"
  #           properties:
  #             title:
  #               type: "string"
  #             completed:
  #               type: "boolean"
  #   responses:
  #     "200":
  #       description: "Todo updated successfully"
  # delete:
  #   summary: "Delete a todo by ID"
  #   parameters:
  #     - in: path
  #       name: id
  #       required: true
  #       schema:
  #         type: integer
  #   responses:
  #     "204":
  #       description: "Todo deleted successfully"
